name: receipt_catcher
description: App for managing receipts from stores and etc
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Google Auth & Sheets
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  http: ^1.2.0

  # File picking
  file_picker: ^8.0.3

  # AI – Google Gemini
  google_generative_ai: ^0.4.6

  # Utilities
  uuid: ^4.4.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
